hmm this work?

diff --git a/9.0/windows/windowsservercore-1809/Dockerfile b/9.0/windows/windowsservercore-1809/Dockerfile
--- a/9.0/windows/windowsservercore-1809/Dockerfile
+++ b/9.0/windows/windowsservercore-1809/Dockerfile
@@ -4,12 +4,41 @@ FROM mcr.microsoft.com/windows/servercore:1809
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 
 # PATH isn't actually set in the Docker image, so we have to set it from within the container
-RUN $newPath = ('{0}\bin;C:\Program Files\ghc\bin;{1}' -f $env:GOPATH, $env:PATH); \
+RUN $newPath = ('{0}\bin;C:\Program Files\ghc\bin;C:\Program Files\cabal-install\bin;{1}' -f $env:GOPATH, $env:PATH); \
 	Write-Host ('Updating PATH: {0}' -f $newPath); \
 	[Environment]::SetEnvironmentVariable('PATH', $newPath, [EnvironmentVariableTarget]::Machine);
 # doing this first to share cache across versions more aggressively
 
-RUN $url = 'https://downloads.haskell.org/~ghc/9.0.2/ghc-9.0.2-x86_64-unknown-mingw32.zip'; \
+# RUN $cabalInstallVersion = '3.6.2.0'; \
+#     $url = (https://downloads.haskell.org/~cabal/cabal-install-{0}/cabal-install-{0}-x86_64-windows.zip' -f $cabalInstallVersion); \
+# 	Write-Host ('Downloading {0} ...' -f $url); \
+# 	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
+# 	Invoke-WebRequest -Uri $url -OutFile 'cabal-install.zip'; \
+# 	\
+# 	$sha256 = '89aa3aa3f76d15182c0d03227639890cd537627ba0bf0ef9ab451fee504b24c6'; \
+# 	Write-Host ('Verifying sha256 ({0}) ...' -f $sha256); \
+# 	if ((Get-FileHash cabal-install.zip -Algorithm sha256).Hash -ne $sha256) { \
+# 		Write-Host 'FAILED!'; \
+# 		exit 1; \
+# 	}; \
+# 	\
+# 	Write-Host 'Expanding ...'; \
+# 	Expand-Archive ghc.zip -DestinationPath C:\; \
+# 	\
+# 	Write-Host 'Moving ...'; \
+# 	Move-Item -Path ('C:\{0}' -f $releaseName) -Destination 'C:\Program Files\ghc'; \
+# 	\
+# 	Write-Host 'Removing ...'; \
+# 	Remove-Item ghc.zip -Force; \
+# 	\
+# 	Write-Host 'Verifying install ("ghc --version") ...'; \
+# 	ghc --version; \
+# 	\
+# 	Write-Host 'Complete.';
+
+RUN $ghcVersion = '9.0.2'; \
+    $releaseName = ('ghc-{0}-x86_64-unknown-mingw32' -f $ghcVersion); \
+    $url = ('https://downloads.haskell.org/~ghc/{0}/{1}.zip' -f $ghcVersion, $releaseName); \
 	Write-Host ('Downloading {0} ...' -f $url); \
 	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
 	Invoke-WebRequest -Uri $url -OutFile 'ghc.zip'; \
@@ -25,7 +54,7 @@ RUN $url = 'https://downloads.haskell.org/~ghc/9.0.2/ghc-9.0.2-x86_64-unknown-mi
 	Expand-Archive ghc.zip -DestinationPath C:\; \
 	\
 	Write-Host 'Moving ...'; \
-	Move-Item -Path C:\ghc-9.0.2-x86_64-unknown-mingw32 -Destination 'C:\Program Files\ghc'; \
+	Move-Item -Path ('C:\{0}' -f $releaseName) -Destination 'C:\Program Files\ghc'; \
 	\
 	Write-Host 'Removing ...'; \
 	Remove-Item ghc.zip -Force; \
