fix: reverting heredocs in Dockerfile template (#167)

diff --git a/9.10/slim-bullseye/Dockerfile b/9.10/slim-bullseye/Dockerfile
--- a/9.10/slim-bullseye/Dockerfile
+++ b/9.10/slim-bullseye/Dockerfile
@@ -3,8 +3,7 @@ FROM debian:bullseye-slim
 ENV LANG=C.UTF-8
 
 # common haskell + stack dependencies
-RUN <<EOT
-    apt-get update && \
+RUN apt-get update && \
     apt-get install -y --no-install-recommends \
         ca-certificates \
         curl \
@@ -23,120 +22,114 @@ RUN <<EOT
         xz-utils \
         zlib1g-dev && \
     rm -rf /var/lib/apt/lists/*
-EOT
+
 
 ARG STACK='3.3.1'
 ARG STACK_RELEASE_KEY='C5705533DA4F78D8664B5DC0575159689BEFB442'
 
-RUN <<EOT
-    set -eux
-    cd /tmp
-    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"
-    STACK_URL="https://github.com/commercialhaskell/stack/releases/download/v${STACK}/stack-${STACK}-linux-$ARCH.tar.gz"
-    # sha256 from https://github.com/commercialhaskell/stack/releases/download/v${STACK}/stack-${STACK}-linux-$ARCH.tar.gz.sha256
-    case "$ARCH" in 
-        'aarch64') 
-            STACK_SHA256='bdd618ea5a9c921417727011f2ecd78987dffa5cee5e741108baf65a9b5b58ab'
-            ;;
-        'x86_64') 
-            STACK_SHA256='88d7e517342c125b0a098d9d578fe53e590618ae4b2427283a27408a1ebd06d8'
-            ;;
-        *) echo >&2 "error: unsupported architecture '$ARCH'" exit 1 ;
-    esac
-    curl -sSL "$STACK_URL" -o stack.tar.gz
-    echo "$STACK_SHA256 stack.tar.gz" | sha256sum --strict --check
-    
-    curl -sSL "$STACK_URL.asc" -o stack.tar.gz.asc
-    GNUPGHOME="$(mktemp -d)"
-    export GNUPGHOME
-    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$STACK_RELEASE_KEY"
-    gpg --batch --verify stack.tar.gz.asc stack.tar.gz
-    gpgconf --kill all
-    
-    tar -xf stack.tar.gz -C /usr/local/bin --strip-components=1 "stack-$STACK-linux-$ARCH/stack"
-    stack config set system-ghc --global true
-    stack config set install-ghc --global false
-    
-    rm -rf /tmp/*
-    
+RUN set -eux; \
+    cd /tmp; \
+    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
+    STACK_URL="https://github.com/commercialhaskell/stack/releases/download/v${STACK}/stack-${STACK}-linux-$ARCH.tar.gz"; \
+    # sha256 from https://github.com/commercialhaskell/stack/releases/download/v${STACK}/stack-${STACK}-linux-$ARCH.tar.gz.sha256 \
+    case "$ARCH" in \
+        'aarch64') \
+            STACK_SHA256='bdd618ea5a9c921417727011f2ecd78987dffa5cee5e741108baf65a9b5b58ab'; \
+            ;; \
+        'x86_64') \
+            STACK_SHA256='88d7e517342c125b0a098d9d578fe53e590618ae4b2427283a27408a1ebd06d8'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture '$ARCH'" exit 1 ; \
+    esac; \
+    curl -sSL "$STACK_URL" -o stack.tar.gz; \
+    echo "$STACK_SHA256 stack.tar.gz" | sha256sum --strict --check; \
+    \
+    curl -sSL "$STACK_URL.asc" -o stack.tar.gz.asc; \
+    GNUPGHOME="$(mktemp -d)"; \
+    export GNUPGHOME; \
+    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$STACK_RELEASE_KEY"; \
+    gpg --batch --verify stack.tar.gz.asc stack.tar.gz; \
+    gpgconf --kill all; \
+    \
+    tar -xf stack.tar.gz -C /usr/local/bin --strip-components=1 "stack-$STACK-linux-$ARCH/stack"; \
+    stack config set system-ghc --global true; \
+    stack config set install-ghc --global false; \
+    \
+    rm -rf /tmp/*; \
+    \
     stack --version;
-EOT
 
 ARG CABAL_INSTALL='3.14.1.1'
 ARG CABAL_INSTALL_RELEASE_KEY='EAF2A9A722C0C96F2B431CA511AAD8CEDEE0CAEF'
 
-RUN <<EOT
-    set -eux
-    cd /tmp
-    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"
-    CABAL_INSTALL_TAR="cabal-install-$CABAL_INSTALL-$ARCH-linux-deb11.tar.xz"
-    CABAL_INSTALL_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/$CABAL_INSTALL_TAR"
-    CABAL_INSTALL_SHA256SUMS_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS"
-    # sha256 from https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS
-    case "$ARCH" in
-        'aarch64')
-            CABAL_INSTALL_SHA256='5e8c47a055d5b744741039a7061ee43ec7d080d1251784e7a4cd836403e42523'
-            ;;
-        'x86_64')
-            CABAL_INSTALL_SHA256='41b85bb25fa654e4b79169014b9142fe696ff35e002e043caa0e52d65204ba8a'
-            ;;
-        *) echo >&2 "error: unsupported architecture '$ARCH'"; exit 1 ;;
-    esac
-    curl -fSL "$CABAL_INSTALL_URL" -o cabal-install.tar.gz
-    echo "$CABAL_INSTALL_SHA256 cabal-install.tar.gz" | sha256sum --strict --check
-
-    curl -sSLO "$CABAL_INSTALL_SHA256SUMS_URL"
-    curl -sSLO "$CABAL_INSTALL_SHA256SUMS_URL.sig"
-    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME
-    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$CABAL_INSTALL_RELEASE_KEY"
-    gpg --batch --verify SHA256SUMS.sig SHA256SUMS
-    # confirm we are verifying SHA256SUMS that matches the release + sha256
-    grep "$CABAL_INSTALL_SHA256  $CABAL_INSTALL_TAR" SHA256SUMS
-    gpgconf --kill all;
-
-    tar -xf cabal-install.tar.gz -C /usr/local/bin
-
-    rm -rf /tmp/*
-
+RUN set -eux; \
+    cd /tmp; \
+    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
+    CABAL_INSTALL_TAR="cabal-install-$CABAL_INSTALL-$ARCH-linux-deb11.tar.xz"; \
+    CABAL_INSTALL_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/$CABAL_INSTALL_TAR"; \
+    CABAL_INSTALL_SHA256SUMS_URL="https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS"; \
+    # sha256 from https://downloads.haskell.org/~cabal/cabal-install-$CABAL_INSTALL/SHA256SUMS \
+    case "$ARCH" in \
+        'aarch64') \
+            CABAL_INSTALL_SHA256='5e8c47a055d5b744741039a7061ee43ec7d080d1251784e7a4cd836403e42523'; \
+            ;; \
+        'x86_64') \
+            CABAL_INSTALL_SHA256='41b85bb25fa654e4b79169014b9142fe696ff35e002e043caa0e52d65204ba8a'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture '$ARCH'"; exit 1 ;; \
+    esac; \
+    curl -fSL "$CABAL_INSTALL_URL" -o cabal-install.tar.gz; \
+    echo "$CABAL_INSTALL_SHA256 cabal-install.tar.gz" | sha256sum --strict --check; \
+    \
+    curl -sSLO "$CABAL_INSTALL_SHA256SUMS_URL"; \
+    curl -sSLO "$CABAL_INSTALL_SHA256SUMS_URL.sig"; \
+    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
+    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$CABAL_INSTALL_RELEASE_KEY"; \
+    gpg --batch --verify SHA256SUMS.sig SHA256SUMS; \
+    # confirm we are verifying SHA256SUMS that matches the release + sha256 \
+    grep "$CABAL_INSTALL_SHA256  $CABAL_INSTALL_TAR" SHA256SUMS; \
+    gpgconf --kill all; \
+    \
+    tar -xf cabal-install.tar.gz -C /usr/local/bin; \
+    \
+    rm -rf /tmp/*; \
+    \
     cabal --version
-EOT
 
 ARG GHC='9.10.3'
 ARG GHC_RELEASE_KEY='88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4'
 
-RUN <<EOT
-    set -eux
-    cd /tmp
-    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"
-    GHC_URL="https://downloads.haskell.org/~ghc/$GHC/ghc-$GHC-$ARCH-deb11-linux.tar.xz"
-    # sha256 from https://downloads.haskell.org/~ghc/$GHC/SHA256SUMS
-    case "$ARCH" in
-        'aarch64')
-            GHC_SHA256='052789dfe7f6fba6dc3822de0da272e8a5bd358c37adae17d8e82cff39bc1008'
-            ;;
-        'x86_64')
-            GHC_SHA256='b6bbd3514e0cdb9db350812a003bb7c670c58d99779086fbe41092b019548924'
-            ;;
-        *) echo >&2 "error: unsupported architecture '$ARCH'" ; exit 1 ;;
-    esac
-    curl -sSL "$GHC_URL" -o ghc.tar.xz
-    echo "$GHC_SHA256 ghc.tar.xz" | sha256sum --strict --check
-
-    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME
-    curl -sSL "$GHC_URL.sig" -o ghc.tar.xz.sig
-    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$GHC_RELEASE_KEY"
-    gpg --batch --verify ghc.tar.xz.sig ghc.tar.xz
-    gpgconf --kill all
-
-    tar xf ghc.tar.xz
-    cd "ghc-$GHC-$ARCH-unknown-linux"
-    ./configure --prefix "/opt/ghc/$GHC"
-    make install
-
-    rm -rf /tmp/*
-
+RUN set -eux; \
+    cd /tmp; \
+    ARCH="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)"; \
+    GHC_URL="https://downloads.haskell.org/~ghc/$GHC/ghc-$GHC-$ARCH-deb11-linux.tar.xz"; \
+    # sha256 from https://downloads.haskell.org/~ghc/$GHC/SHA256SUMS \
+    case "$ARCH" in \
+        'aarch64') \
+            GHC_SHA256='052789dfe7f6fba6dc3822de0da272e8a5bd358c37adae17d8e82cff39bc1008'; \
+            ;; \
+        'x86_64') \
+            GHC_SHA256='b6bbd3514e0cdb9db350812a003bb7c670c58d99779086fbe41092b019548924'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture '$ARCH'" ; exit 1 ;; \
+    esac; \
+    curl -sSL "$GHC_URL" -o ghc.tar.xz; \
+    echo "$GHC_SHA256 ghc.tar.xz" | sha256sum --strict --check; \
+    \
+    GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
+    curl -sSL "$GHC_URL.sig" -o ghc.tar.xz.sig; \
+    gpg --batch --keyserver keyserver.ubuntu.com --receive-keys "$GHC_RELEASE_KEY"; \
+    gpg --batch --verify ghc.tar.xz.sig ghc.tar.xz; \
+    gpgconf --kill all; \
+    \
+    tar xf ghc.tar.xz; \
+    cd "ghc-$GHC-$ARCH-unknown-linux"; \
+    ./configure --prefix "/opt/ghc/$GHC"; \
+    make install; \
+    \
+    rm -rf /tmp/*; \
+    \
     "/opt/ghc/$GHC/bin/ghc" --version
-EOT
 
 ENV PATH=/root/.cabal/bin:/root/.local/bin:/opt/ghc/${GHC}/bin:$PATH
 
